Basic Artificial Neural Network
Aman22sharma/Hacktoberfest2021_beginner pull request #63
Opened 2021-10-02 07:24 UTC by Mgeethabhargava

Basic Artificial Neural Network

2021-10-02 13:00 UTC, Aman22sharma requested changes
Please follow the readme.MD (Contribution guidelines). You need to maintain a proper file structure

2021-10-03 02:12 UTC, Mgeethabhargava commented
made changes as said by you

2021-10-03 05:22 UTC, Aman22sharma approved these changes

2021-10-03 05:22 UTC, merged

2021-10-03 05:22 UTC, Aman22sharma commented
Thank you for your contribution